defmodule Ashtypea.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :role, :text, null: false, default: "user"
    end

    alter table(:posts) do
      add :user_id,
          references(:users,
            column: :id,
            name: "posts_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end
  end

  def down do
    drop constraint(:posts, "posts_user_id_fkey")

    alter table(:posts) do
      remove :user_id
    end

    alter table(:users) do
      remove :role
    end
  end
end
